apiVersion: v1
kind: Service
metadata:
  name: goalsapp-ui-service
spec:
  type: NodePort
  selector:
    app: goalsapp-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30020
