apiVersion: v1
kind: Service
metadata:
  name: goalsapp-api-service
spec:
  type: NodePort
  selector:
    app: goalsapp-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30020
